spring:
  application:
    name: foro_hub
  datasource:
    url: jdbc:postgresql://${DB_HOST}${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-stacktrace: never